### ISSUE TITLE
rename timetable project to timetable

### ISSUE THREAD

**Issue by ClintCWC** [ClintCWC/TimetablesFrontEnd#11]
Lose the word project, it is simply a timetable.

**Comment by ClintCWC** [comment]
done

**Comment by BrianB3103** [comment]
not fixed as discussed

**Comment by ClintCWC** [comment]
fixed, just need to recompile

**Comment by BrianB3103** [comment]
there are still 2 references to project in different places as you step through the sequence, on the timetable page and on the dayset page
