### ISSUE TITLE
introduce breadcrumb navigation

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#15]
introduce breadcrumb navigation

**Comment by ClintCWC** [comment]
done

**Comment by BrianB3103** [comment]
Looks good, however there is now a naming conflict, so can we please streamline this by...

The main tab at the very top of the page, rename TIMETABLES
Clicking on that will take you to TIMETABLE DIRECTORY
Clicking on any in the directory will take you to TIMETABLE, 
through to DAYSETS as now

So the breadcrumb sequence becomes HOME - TIMETABLES - TIMETABLE DIRECTORY - TIMETABLE - DAYSET

I guess that because Locations, Routeing rules etc etc have their own subtabs that they dont get crumbed?

**Comment by ClintCWC** [comment]
this is issue is now closed, as is was to introduce a breadcrumb which is done. i don't agree with the breadcrumb sequence suggested.

if it needs to be changed at all it can be
HOME - TIMETABLE DIRECTORY - TIMETABLE - DAYSET in lower case as timetables and timetable directory are the same thing.
