### ISSUE TITLE
timetable directory inital sort order

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#2]
Please make the default sort by NAME ascending and to remember this. Regardless of what view I select, every time i come back to it it has scrambled again

**Comment by ClintCWC** [comment]
now remembers previous sort choice.

**Comment by BrianB3103** [comment]
not working as discussed

**Comment by BrianB3103** [comment]
Even in Firefox, still not working

**Comment by ClintCWC** [comment]
i think this is fixed?
