### ISSUE TITLE
Remove word copy from titles of daysets that have been copied

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#20]
After copying a dayset it appends copy to the end, if you copy a copy it appends copy copy to the end

**Comment by ClintCWC** [comment]
it is intended behavior, so the user can see at a glance which is the copy and which is the orignal

**Comment by BrianB3103** [comment]
not important, please remove

**Comment by ClintCWC** [comment]
done but will only affect new copies
