### ISSUE TITLE
Locations/station codes/tiplocs not always correct

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#25]
When adding a location by name it can generate the wrong code for stations that have had multiple tiplocs glued together, eg typing Reading will generate RDZ which is wrong, should be RDG, because
RDZ represents just one of the glued together tiplocs

Adding a location by unique code appears to be fine, eg typing RDG works, but adding by code can only ever be a secondary method as not everyone, not even me, knows every code of every station

**Comment by kaigoh** [comment]
Done.

**Comment by BrianB3103** [comment]
Just created a new table called AAA test Reading. Entered correct selection of RDG and get no output at all

**Comment by kaigoh** [comment]
Looks ok to me?

![image](https://user-images.githubusercontent.com/544634/71360902-3fd6a400-2589-11ea-8613-be31f42d4763.png)

**Comment by BrianB3103** [comment]
Afraid not, that is a snapshot of only the trains that depart from tiploc RDZ. It has not captured any of the trains that depart from RDG, assuming the point of this exercise was to merger RDZ and RDG into one location

**Comment by kaigoh** [comment]
Fixed!
