### ISSUE TITLE
uid pop up panel

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#31]
The new uid pop up is great but needs a few tweaks to fully match what we have now:

The pop up must be dragable around the screen, atm it is static and hides whatever is beneath it.
Need to be able to open up multiple pop ups and view them side by side.
Full list of info required is: (some are already there)

HEADERS
Operator
id
uid
iuid
STP indicator
Whether an associated train or not
start date (uk format)
end date (uk format)
Days run binary 
Days run human
Whether crosses midnight

GRID
Location (proper name, not tiploc)
Arrive
Pass (light or greyed)
Depart
Platform
Activity
CIF last updated time stamp

**Comment by ClintCWC** [comment]
i did as much as i could there are somethings i just cant add at this stage., and i added tabs so you can tab through the merged services.
