### ISSUE TITLE
add dayset copy and invert function

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#6]
Build copy function, also copy and invert function, so that only 1 dayset ever needs to be fully constructed. This is a priority if we are to have multiple daysets and directions to compare, if not we can only have 1 dayset of 1 direction of each table to compare due to the time needed to build them manually

**Comment by ClintCWC** [comment]
done
you need to go to Dayset locations to reverse the order

**Comment by BrianB3103** [comment]
I see that, but dont see a copy function. Before inverting anything, need the ability to a) copy the fully configged 1st SX dayset to an SO one, then to a SU one, then to invert and repeat. As its stands all that happens is that it overrides the original one.

Would have expected these to be functions in the config area, not the locations area

**Comment by ClintCWC** [comment]
you copy a dayset at the daysets level 
you reverse the locations at the dayset/locations level.

so in english, in the timetable, where you can view previously created dayset, there is acopy icon next to the delete icon, you click this and then it takes you to a dayset creation screen with all the details of the copied dayset already in place.

if you want to reverse the location order, you do that in the locations section.

they are handled separately unlike desktop trainset

would make no sense to place any of this inside a config area.
