### ISSUE TITLE
rework data extract position

### ISSUE THREAD

**Issue by BrianB3103** [ClintCWC/TimetablesFrontEnd#9]
The extract button is currently inside the output tab. Please make it a unique tab between Route manager and output , that way you build, build, build then extract. The output tab should be nothing more than the place you view the output and edit it. However, please dont remove the extract tab completely from inside the output tab, as there will always be a need to RE-EXTRACT from inside the output. This comment is all about the initial extract which is not a intuitive flow right now

**Comment by ClintCWC** [comment]
i dont get this requirement. if you make it a unique tab. what goes in the content of that table? a copy of the output?

the more i read this the less i like the idea. the data view is were everything is done including refreshing data from cif.

**Comment by BrianB3103** [comment]
Further thought is needed on this - as it stands, with the extract button behind the output button for a single dayset, it is not possible to extract a series of daysets as a group, or a series of timetables as a group. Losing this ability will be a big loss to the user (example, when doing the NRT recently, I just set 188 tables to extract as a group and went away until they were done. As it stands that would be 188 x 6 = 1128 daysets to extract individually. Even GW alone would run to 264.

Currently we can extract from any page by a right click menu, but i know that isnt available in web, so need to rethink this so that we can extract from any page any selected group of things
